variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidrs" {}
variable "private_subnet_az1_cidrs" {}
variable "my_ip_address" {}
variable "ami_id" {}
variable "instance_type" {}
variable "key_name" {}